### PR TITLE
Add order for Level 1 moves in Gen 9

### PR DESCRIPTION
**Pull request by 14239**
Added Level 1 moves' "order" information for Scarlet Violet.
I got the data from Serebii and also verified the moves learned by check wild Pokémon in-game.
(ie. Wood Hammer is the last level 1 move for Mimikyu)

During the sorting process, all of the data was sorted by order for skills learned at the same level, not just Scarlet Violet.
Most of the case were sorted by order already so I think it wouldn't be a problem.

### CODE REVIEW

**Comment by Naramsim** [comment]
Hi, I checked the diff locally on my PC. There are many reorderings that aren't needed. Could you please just submit the updated data?

**Comment by 14239** [comment]
I just fixed it to rearrange only for order I added, please check it out.

**Comment by pokeapi-machine-user** [comment]
A [PokeAPI/api-data](https://github.com/PokeAPI/api-data) refresh has started. In 45 minutes the staging branch of [PokeAPI/api-data](https://github.com/PokeAPI/api-data/tree/staging) will be pushed with the new generated data. <br><br> The staging branch will be deployed in our [staging environment](https://staging.pokeapi.co/api/v2/) and you will be able to review the entire API. <br><br> A Pull Request ([master](https://github.com/PokeAPI/api-data/tree/master)<-[staging](https://github.com/PokeAPI/api-data/tree/staging)) will be also created at [PokeAPI/api-data](https://github.com/PokeAPI/api-data/pulls) and assigned to the PokeAPI Core team to be reviewed. If approved and merged new data will soon be available worldwide at [pokeapi.co](https://pokeapi.co/api/v2/).

**Comment by pokeapi-machine-user** [comment]
The updater script has finished its job and has now opened a Pull Request towards [PokeAPI/api-data](https://github.com/PokeAPI/api-data/pulls) with the updated data. <br><br> You can see the Pull Request deployed at our [staging environment](https://staging.pokeapi.co/api/v2/) when [CircleCI deploy](https://app.circleci.com/pipelines/github/PokeAPI/deploy) will be finished (_check the started time of the last build_).

**Pull request merged**
