### PR TITLE
Fixed Shape IDs for Gen IX Pokémon

### PR DESCRIPTION
**Pull request by erezushi**
Fixed shape IDs for Gen IX Pokémon, according to the filters on the mobile version of Pokémon HOME

### CODE REVIEW

**Comment by Naramsim** [comment]
Hi! Is it possible for a pokemon to have different shapes for different games?

**Comment by erezushi** [comment]
So far, there were only 12 Pokémon that had their shape change between games, 11 changed in XY, 1 in ORAS, so basically yes, but it's rare.
What is possible is different forms having different shapes. Specifically in Gen IX, you have a difference between Zero and Hero Palafin, Chest and Roaming Gimmighoul, and between regular Terapagos and its other forms. Here I went with their "default" forms

**Comment by Naramsim** [comment]
Ok, so we would need a changelog table here as well. Maybe you can open an issue documenting it and maybe someone will work on it.

**Comment by Naramsim** [comment]
In the meantime I'll merge the PR.

**Comment by pokeapi-machine-user** [comment]
A [PokeAPI/api-data](https://github.com/PokeAPI/api-data) refresh has started. In ~45 minutes the staging branch of [PokeAPI/api-data](https://github.com/PokeAPI/api-data/tree/staging) will be pushed with the new generated data. <br><br> The staging branch will be deployed in our [staging environment](https://staging.pokeapi.co/api/v2/) and the entire API will be ready to review. <br><br> A Pull Request ([master](https://github.com/PokeAPI/api-data/tree/master)<-[staging](https://github.com/PokeAPI/api-data/tree/staging)) will be also created at [PokeAPI/api-data](https://github.com/PokeAPI/api-data/pulls) and assigned to the PokeAPI Core team to be reviewed. If approved and merged new data will soon be available worldwide at [pokeapi.co](https://pokeapi.co/api/v2/).

**Comment by pokeapi-machine-user** [comment]
The updater script has finished its job and has now opened a Pull Request towards [PokeAPI/api-data](https://github.com/PokeAPI/api-data/pulls) with the updated data. <br><br> The Pull Request can be seen deployed in our [staging environment](https://staging.pokeapi.co/api/v2/) when [CircleCI deploy](https://app.circleci.com/pipelines/github/PokeAPI/deploy) will be finished (_check the start time of the last build_).

**Pull request merged**
