### PR TITLE
Fix move types and localize

### PR DESCRIPTION
**Pull request by giginet**
Sorry, The change I submitted on #783 and #788 is wrong. 🙇 

- English Move names and Chinese names are opposite
- All new moves' `type_id` is wrong. I fixed these columns.
- I modified some `generation_id`. Moves since Legend Arceus should be `8`th generation

I'm so sorry to submit the wrong data.

I checked my local database, it may be correct.

Screenshot 2022-12-14 at 4 16 16

### CODE REVIEW

**Comment by Naramsim** [comment]
Ok, don't worry. Do you think I should merge this PR now? Or should other PRs be merged beforehand?

**Comment by giginet** [comment]
@Naramsim This PR is independent of other PRs.
The current master contains wrong data. So could you merge this soon after checking you?

**Review by Thorbenl — APPROVED** [review]
LGTM :)

**Comment by pokeapi-machine-user** [comment]
A [PokeAPI/api-data](https://github.com/PokeAPI/api-data) refresh has started. In 45 minutes the staging branch of [PokeAPI/api-data](https://github.com/PokeAPI/api-data/tree/staging) will be pushed with the new generated data. <br><br> The staging branch will be deployed in our [staging environment](https://staging.pokeapi.co/api/v2/) and you will be able to review the entire API. <br><br> A Pull Request ([master](https://github.com/PokeAPI/api-data/tree/master)<-[staging](https://github.com/PokeAPI/api-data/tree/staging)) will be also created at [PokeAPI/api-data](https://github.com/PokeAPI/api-data/pulls) and assigned to the PokeAPI Core team to be reviewed. If approved and merged new data will soon be available worldwide at [pokeapi.co](https://pokeapi.co/api/v2/).

**Pull request merged**
