### PR TITLE
Update http -> https for pokeapi endpoints in home.html

### PR DESCRIPTION
**Pull request by HipsterBrown**
Fixes https://github.com/PokeAPI/pokeapi/issues/312

### CODE REVIEW

**Comment by Naramsim** [comment]
Hi @HipsterBrown, thanks for the PR.

We can merge it, but before merging I would suggest a thing. Maybe in future, we will drop Cloudflare and thus run only over HTTP protocol. So it would be nice that if pokeapi.co is loaded using HTTPS it shows https:// and if it is loaded using HTTP is shows http://

We can use `location.protocol` to determine which protocol is the page loaded

**Comment by HipsterBrown** [comment]
@Naramsim That's an interesting case to think about. 

Using something like `location.protocol` would only catch the cases on the site pages, so some manual work would still be needed to update the markdown pages across this repo. 

I'm curious about how the `url` resources are generated for the API because that seems to stay updated. I.e the `results` from `/api/v2/pokemon/`:

```json
{
	"count": 949,
	"previous": null,
	"results": [
		{
			"url": "https://pokeapi.co/api/v2/pokemon/1/",
			"name": "bulbasaur"
		},
		...
	],
	"next": "https://pokeapi.co/api/v2/pokemon/?limit=20&offset=20"
}
```

How does that `url` key stay updated?

**Comment by Naramsim** [comment]
Based on the client request. When you could query the API using HTTP the returned URLs where http:// if you were using http, https:// if you were using https. Now it returns only https because is the only protocol allowed.

**Comment by Naramsim** [comment]
Closing since the frontend moved here https://github.com/PokeAPI/pokeapi.co

**Pull request closed without merging**
