### PR TITLE
Update data automatically and enable staging deployment

### PR DESCRIPTION
**Pull request by Naramsim**
_PRs are ready, I would start by reading this one and then moving to https://github.com/PokeAPI/deploy/pull/10_

---

This PR will be used to describe major changes in the way we update our application pokeapi.co seen as a whole (API+frontpage+docs). 

Right now to deploy the API we need to run a script on our PCs and then merge a PR. The script requires docker, takes a long time and when it's done will open a PR towards PokeAPI/api-data with the new data. The new data there is actually impossible to visualize since thousands of files were probably updated. So this PR proposes two solutions to our two problems:

- Running the updater-script somewhere else, not on our PCs, and in an automatic manner
- Enabling a staging environment to check what we are going to deploy
- _(bonus)_ Having a way to deploy a PR without merging it to the `master` branch

### How?

Part of this PR adds a way to update productive data effortlessly. It uses the old [`updater bot`](https://github.com/PokeAPI/api-data/tree/master/updater) and runs it in CircleCI, then pushes the new data to a `PokeAPI/api-data` branch (called `staging`) and opens a Pull Request in the `api-data` repository, asking to merge `staging` into `master`.

The workflow is:

1. A PR on `PokeAPI/pokeapi` is merged in the `master` branch, thus the `master` is pushed/committed
1. CircleCI is notified and runs the tests and a new special script `Resources/scripts/updater.sh`
1. This updater.sh script is substantially a glue-script of the old https://github.com/PokeAPI/api-data/blob/master/updater/cmd.bash written by @sargunv.
Basically the two scripts generate new data using the updated `master` branch of `PokeAPI/pokeapi` and push it to `PokeAPI/api-data`'s `staging` branch, the push is done by the new [pokeapi-machine-user](https://github.com/pokeapi-machine-user). A cool thing is that the new machine user will keep us updated about how things are going inside CircleCI. It is programmed to send some messages to the recently merged PR. 
1. The script creates also a new PR in `PokeAPI/api-data` from the `staging` branch into the `master` one. This is cool because the `staging` branch will be deployed in a new Firebase staging environment thanks to the other PRs linked down below. So we will be able to check how our updated application as a whole (API+frontpage+docs) will look like.
1. _Then, if that PR is merged_, the new data will be deployed automatically to the productive Firebase environments. If you want to see how a sample PR from `staging` into `master` looks like you have it here: https://github.com/PokeAPI/api-data/pull/41, over there I forced a `staging` deployment of `PokeAPI/pokeapi`'s `circleci-hook` branch even though it should have run only on the `master` branch, but it was only for testing. Normally the deployment will be done only if the `master` gets pushed.

I think this workflow works well because it takes completely away the hassle of generating the data manually and the risk of deploying broken stuff.

An additional workflow allows us to deploy in the staging environment the content of a PR that hasn't been merged yet. In fact whenever `PokeAPI/pokeapi` or `PokeAPI/pokeapi.co`'s `staging` branches get pushed a new staging deployment will be triggered. So suppose an external user sends us a PR, we will just need to push it to the `staging` branch and in 45 minutes we will have the staging environment reflecting the new changes that PR brings in. 

---

This PR is linked to the following PRs: 
- https://github.com/PokeAPI/deploy/pull/10 
- https://github.com/PokeAPI/pokeapi.co/pull/76 
- https://github.com/PokeAPI/api-data/pull/42 

__When https://github.com/PokeAPI/deploy/pull/10 will be merged we need to change `Resources/scripts/updater.sh#90` and `.circleci/config.yml#43`__

This PR should be merged after https://github.com/PokeAPI/deploy/pull/10 and https://github.com/PokeAPI/api-data/pull/42

### CODE REVIEW

**Comment by Naramsim** [comment]
Don't merge, it's a test

**Comment by pokeapi-machine-user** [comment]
A [PokeAPI/api-data](https://github.com/PokeAPI/api-data) refresh has started. If everything works out in 30 minutes a Pull Request will be created and assigned to the PokeAPI Core team to be reviewed. If approved and merged new data will soon be available worldwide.

**Comment by pokeapi-machine-user** [comment]
A [PokeAPI/api-data](https://github.com/PokeAPI/api-data) refresh has started. If everything works out in 30 minutes a Pull Request will be created and assigned to the PokeAPI Core team to be reviewed. If approved and merged new data will soon be available worldwide.

**Comment by pokeapi-machine-user** [comment]
A [PokeAPI/api-data](https://github.com/PokeAPI/api-data) refresh has started. If everything works out in 30 minutes a Pull Request will be created and assigned to the PokeAPI Core team to be reviewed. If approved and merged new data will soon be available worldwide.

**Comment by pokeapi-machine-user** [comment]
A [PokeAPI/api-data](https://github.com/PokeAPI/api-data) refresh has started. If everything works out in 30 minutes a Pull Request will be created and assigned to the PokeAPI Core team to be reviewed. If approved and merged new data will soon be available worldwide.

**Comment by pokeapi-machine-user** [comment]
A [PokeAPI/api-data](https://github.com/PokeAPI/api-data) refresh has started. If everything works out in 30 minutes a Pull Request will be created and assigned to the PokeAPI Core team to be reviewed. If approved and merged new data will soon be available worldwide.

**Comment by pokeapi-machine-user** [comment]
The updater script has finished its job and has opened a Pull Request [PokeAPI/api-data](https://github.com/PokeAPI/api-data) with the updated data.

**Comment by pokeapi-machine-user** [comment]
A [PokeAPI/api-data](https://github.com/PokeAPI/api-data) refresh has started. If everything works out in 30 minutes a Pull Request will be created and assigned to the PokeAPI Core team to be reviewed. If approved and merged new data will soon be available worldwide.

**Comment by pokeapi-machine-user** [comment]
A [PokeAPI/api-data](https://github.com/PokeAPI/api-data) refresh has started. If everything works out in 30 minutes a Pull Request will be created and assigned to the PokeAPI Core team to be reviewed. If approved and merged new data will soon be available worldwide.

**Comment by pokeapi-machine-user** [comment]
The updater script couldn't finish it's job. Please check CircleCI's logs.

**Comment by pokeapi-machine-user** [comment]
The updater script has finished its job and has opened a Pull Request [PokeAPI/api-data](https://github.com/PokeAPI/api-data) with the updated data.

**Comment by pokeapi-machine-user** [comment]
A [PokeAPI/api-data](https://github.com/PokeAPI/api-data) refresh has started. In 45 minutes the staging branch of [PokeAPI/api-data](https://github.com/PokeAPI/api-data/tree/staging) will be pushed with the new generated data. <br><br> The staging branch will be deployed in our [staging environment](https://pokeapi-test-b6137.firebaseapp.com/api/v2/) and you will be able to review the entire API. <br><br> A Pull Request ([master](https://github.com/PokeAPI/api-data/tree/master)<-[staging](https://github.com/PokeAPI/api-data/tree/staging)) will be also created at [PokeAPI/api-data](https://github.com/PokeAPI/api-data/pulls) and assigned to the PokeAPI Core team to be reviewed. If approved and merged new data will soon be available worldwide at [pokeapi.co](https:/pokeapi.co)

**Comment by pokeapi-machine-user** [comment]
A [PokeAPI/api-data](https://github.com/PokeAPI/api-data) refresh has started. In 45 minutes the staging branch of [PokeAPI/api-data](https://github.com/PokeAPI/api-data/tree/staging) will be pushed with the new generated data. <br><br> The staging branch will be deployed in our [staging environment](https://pokeapi-test-b6137.firebaseapp.com/api/v2/) and you will be able to review the entire API. <br><br> A Pull Request ([master](https://github.com/PokeAPI/api-data/tree/master)<-[staging](https://github.com/PokeAPI/api-data/tree/staging)) will be also created at [PokeAPI/api-data](https://github.com/PokeAPI/api-data/pulls) and assigned to the PokeAPI Core team to be reviewed. If approved and merged new data will soon be available worldwide at [pokeapi.co](https:/pokeapi.co)

**Comment by pokeapi-machine-user** [comment]
A [PokeAPI/api-data](https://github.com/PokeAPI/api-data) refresh has started. In 45 minutes the staging branch of [PokeAPI/api-data](https://github.com/PokeAPI/api-data/tree/staging) will be pushed with the new generated data. <br><br> The staging branch will be deployed in our [staging environment](https://pokeapi-test-b6137.firebaseapp.com/api/v2/) and you will be able to review the entire API. <br><br> A Pull Request ([master](https://github.com/PokeAPI/api-data/tree/master)<-[staging](https://github.com/PokeAPI/api-data/tree/staging)) will be also created at [PokeAPI/api-data](https://github.com/PokeAPI/api-data/pulls) and assigned to the PokeAPI Core team to be reviewed. If approved and merged new data will soon be available worldwide at [pokeapi.co](https:/pokeapi.co)

**Comment by pokeapi-machine-user** [comment]
The updater script has finished its job and has now opened a Pull Request towards [PokeAPI/api-data](https://github.com/PokeAPI/api-data/pulls) with the updated data. <br><br> You can see the Pull Request deployed at our [staging environment](https://pokeapi-test-b6137.firebaseapp.com/api/v2/) when [CircleCI deploy](https://app.circleci.com/pipelines/github/PokeAPI/deploy) will be finished (_check the started time of the last build_)

**Comment by pokeapi-machine-user** [comment]
A [PokeAPI/api-data](https://github.com/PokeAPI/api-data) refresh has started. In 45 minutes the staging branch of [PokeAPI/api-data](https://github.com/PokeAPI/api-data/tree/staging) will be pushed with the new generated data. <br><br> The staging branch will be deployed in our [staging environment](https://pokeapi-test-b6137.firebaseapp.com/api/v2/) and you will be able to review the entire API. <br><br> A Pull Request ([master](https://github.com/PokeAPI/api-data/tree/master)<-[staging](https://github.com/PokeAPI/api-data/tree/staging)) will be also created at [PokeAPI/api-data](https://github.com/PokeAPI/api-data/pulls) and assigned to the PokeAPI Core team to be reviewed. If approved and merged new data will soon be available worldwide at [pokeapi.co](https:/pokeapi.co)

**Comment by pokeapi-machine-user** [comment]
The updater script has finished its job and has now opened a Pull Request towards [PokeAPI/api-data](https://github.com/PokeAPI/api-data/pulls) with the updated data. <br><br> You can see the Pull Request deployed at our [staging environment](https://pokeapi-test-b6137.firebaseapp.com/api/v2/) when [CircleCI deploy](https://app.circleci.com/pipelines/github/PokeAPI/deploy) will be finished (_check the started time of the last build_)

**Pull request merged**
