### PR TITLE
Fixed some missing information in USUM data wrt abilities and moves

### PR DESCRIPTION
**Pull request by Amaterasu5**
Hi! So with regards to my issue [here](https://github.com/PokeAPI/pokeapi/issues/532), I updated the placeholder effect text for abilities and moves introduced in USUM. This includes:
**Light That Burns The Sky**
**Splintered Stormshards**
**Let's Snuggle Forever**
**Plasma Fists**
**Clangorous Soulblaze**
**Mind Blown**
**Photon Geyser**
**Neuroforce**

### CODE REVIEW

**Comment by Naramsim** [comment]
Thanks for the PR! 

Just out of curiosity, where did you get the texts?

**Review by Naramsim — APPROVED** [review]

**Comment by Amaterasu5** [comment]
I grabbed everything from Bulbapedia and cross referenced with serebii.net!

**Comment by Naramsim** [comment]
Could you direct this PR against `PokeAPI/pokedex`?

There we have another similar one for the abilities, so I'd like to compare them. Thanks!

**Comment by Amaterasu5** [comment]
Sure thing, should I close this one or keep it open?

**Comment by Naramsim** [comment]
You can close it, thanks!

**Pull request closed without merging**
