### PR TITLE
Adding giants cap location, and gen 8 and hisui location areas

### PR DESCRIPTION
**Pull request by DaltonSW**
Submitting this again after I made a mistake on the last PR somehow

Adding Gen 8 and Hisui location areas to setup a baseline for adding encounter information

### CODE REVIEW

**Comment by Naramsim** [comment]
I'll merge this in! If you spot mistakes in the future we can revert or change the data. 

Are you able to build and test the API locally on your PC? That would help you understand the logic. So you can add the data and check if everything breaks and check the new data.

**Comment by DaltonSW** [comment]
All the info on the last PR was correct, the "mistake" was that I somehow closed it prematurely by doing something that I thought was a necessary step. This is pretty much my first foray into PRs and public contribution, so I'm going through some growing pains 😅

**Comment by pokeapi-machine-user** [comment]
A [PokeAPI/api-data](https://github.com/PokeAPI/api-data) refresh has started. In ~45 minutes the staging branch of [PokeAPI/api-data](https://github.com/PokeAPI/api-data/tree/staging) will be pushed with the new generated data. <br><br> The staging branch will be deployed in our [staging environment](https://staging.pokeapi.co/api/v2/) and the entire API will be ready to review. <br><br> A Pull Request ([master](https://github.com/PokeAPI/api-data/tree/master)<-[staging](https://github.com/PokeAPI/api-data/tree/staging)) will be also created at [PokeAPI/api-data](https://github.com/PokeAPI/api-data/pulls) and assigned to the PokeAPI Core team to be reviewed. If approved and merged new data will soon be available worldwide at [pokeapi.co](https://pokeapi.co/api/v2/).

**Comment by pokeapi-machine-user** [comment]
The updater script has finished its job and has now opened a Pull Request towards [PokeAPI/api-data](https://github.com/PokeAPI/api-data/pulls) with the updated data. <br><br> The Pull Request can be seen deployed in our [staging environment](https://staging.pokeapi.co/api/v2/) when [CircleCI deploy](https://app.circleci.com/pipelines/github/PokeAPI/deploy) will be finished (_check the start time of the last build_).

**Pull request merged**
