### PR TITLE
Upgrade to Python 3.7 and Django 2.1.2

### PR DESCRIPTION
**Pull request by cmmartti**
This pull request resolves issue #301.

Simultaneously upgrade Python to 3.7 and Django to 2.1.2. All other dependencies are also updated to their most recent versions. With the help of [2to3](https://docs.python.org/2/library/2to3.html), manually correct all incompatible code. Surprisingly, there wasn't much. Whoever wrote the initial code (@zaneadix and @phalt) did a good job of staying compatible with Python3.

All tests pass. The database build script was also tested and corrected.

### CODE REVIEW

**Comment by cmmartti** [comment]
I'm running into a couple of issues with the Flake8 linter. Flake8 hasn't been updated in nearly a year, so it doesn't support the most recent version of pycodestyle, which fixed a bug that throws an error in Python 3.7 (issue at PyCQA/pycodestyle#728).

Also, for some reason, Flake8 isn't respecting the `#NOQA` comment that skips linting on specific lines, and there are a number of modules that use `*` star imports. This could be "fixed" by adding error code `F405` to the ignore list, but doesn't fix the underlying problem, which has me stumped.

Options:
- Disable linting until it works with Python 3.7
- Switch to a different linter
- Downgrade to Python 3.6

Thoughts?

**Comment by Naramsim** [comment]
I'd say to just switch the linter. PyLint should work well. I wouldn't
downgrade Python only because the linter doesn't work.

**Comment by cmmartti** [comment]
Okay, it should be good now. I switched the linter to PyLint and adjusted the default configuration to something sane, then fixed the errors and warnings that were detected.

**Comment by sargunv** [comment]
The close was accidental, looks good. The new linter does make me wonder how close we are to black's formatting now.

**Pull request merged**
