### PR TITLE
Added missing sprites for pokemon ids 803-807.

### PR DESCRIPTION
**Pull request by ymin1103**
`dcd583e` Added missing sprites for pokemon ids 803-807 for `front_default` and `shiny_front_default`

All resources in PNG files are from <a href="https://pokemondb.net/sprites">pokemondb.net</a>.

### CODE REVIEW

**Comment by Naramsim** [comment]
Thanks!!

**Comment by Naramsim** [comment]
Could you also open a PR here: https://github.com/PokeAPI/sprites?

**Comment by ymin1103** [comment]
Thanks. I checked the repo and found that there are sprites for pokemon ids 803-807 but different from things I have commited. So which one is better?

**Comment by Naramsim** [comment]
Hmm, maybe you can send us a PR there so we can diff them online 😄

**Comment by ymin1103** [comment]
Got it. I send a <a href="https://github.com/PokeAPI/sprites/pull/10">PR in the repo. </a>

**Pull request closed without merging**
