### PR TITLE
Fix type error for Pokemon/location_area_encounters

### PR DESCRIPTION
**Pull request by relrod**
The API returns a list, not a string

Signed-off-by: Ricky Elrod <ricky@elrod.me>

### CODE REVIEW

**Comment by sargunster** [comment]
Actually, it returns a path (string) to a list resource

http://pokeapi.co/api/v2/pokemon/10/

**Comment by relrod** [comment]
@sargunster ah, then the example here is wrong: https://pokeapi.co/docsv2/#pokemon

That is what I was testing with.

**Comment by sargunster** [comment]
Yeah, the example is outdated. Feel free to fix it.

**Comment by relrod** [comment]
@sargunster I'll do future testing with actual API responses. And if I find some time, I'll go through the examples and update them as needed.

**Pull request closed without merging**
