### PR TITLE
Fix Gen/Region/Version data inconsistencies for Gen9

### PR DESCRIPTION
**Pull request by Pythonic-Rainbow**
Legend Arceus is considered a part of Gen8 on Wikipedia and Bulbapedia. However, it is a special case because it has a different main region from SwSh. 

LA is indeed gen8 in version_groups.csv, but some of the data in other csv files are inconsistent. I assume that LA is a part of gen8 in the API. If so, there will be 2 main regions for gen8, but the `/generation` endpoint specifies `main_region` as a single Region attribute. What are your plans on this problem?

Another example is that `/region/9` (LA:Hisui) currently lists gen9 as its main generation, and `/region/10` (SV:Paldea) has no main generation. My commit should swap the results, but Hisui will have no main generation.

### CODE REVIEW

**Comment by Naramsim** [comment]
@tillfox @giginet do you have some thoughts about this issue?

**Comment by tillfox** [comment]
> @tillfox @giginet do you have some thoughts about this issue?

It seems that @Pythonic-Rainbow has fixed problems in "versions.csv", "version_group_regions.csv" and "generations.csv"... which are the other inconsistencies? 
Main region for 8th gen is Galar, main region for 9th gen is Paldea, everything is correct. Every Pokemon generation by now has just a main region, it makes sense, unless they create a 10th gen game set in two different regions simultaneously...

**Comment by Pythonic-Rainbow** [comment]
> > @tillfox @giginet do you have some thoughts about this issue?
> 
> It seems that @Pythonic-Rainbow has fixed problems in "versions.csv", "version_group_regions.csv" and "generations.csv"... which are the other inconsistencies? Main region for 8th gen is Galar, main region for 9th gen is Paldea, everything is correct. Every Pokemon generation by now has just a main region, it makes sense, unless they create a 10th gen game set in two different regions simultaneously...

Yes you're right. Every gen so far has just 1 main region. I thought Hisui is another main region but I did some more research on Bulbapedia and looks like it is just Sinnoh, which is Gen4 main region.

Then yeah, my question is invalid. Sorry for the confusion.

**Comment by Pythonic-Rainbow** [comment]
I've also added version names, taken from [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_Scarlet_and_Violet#In_other_languages).   

But why are there 3 Japanese locales in https://github.com/PokeAPI/pokeapi/blob/6c3c68a91bb24437f1396c7e3af00d0a9d69a70c/data/v2/csv/languages.csv ? I don't see Roomaji being used anywhere in the csv files, and ID 11 is identical to ID 1 in all the *names.csv that I've found

**Review by giginet — APPROVED** [review]
Looks good.

> Hisui will have no main generation.

I don't have any concerns about this.

**Comment by giginet** [comment]
> I don't see Roomaji being used anywhere in the csv files, and ID 11 is identical to ID 1 in all the *names.csv that I've found

I'm native Japanese. You don't need to set romaji names.

ID 1 and 11 are not identical. ID 1 is ja, and ID 11 is ja without Kanji.
In version names, they seem to be the same. However, flavor texts are different.

**Comment by Pythonic-Rainbow** [comment]
> > I don't see Roomaji being used anywhere in the csv files, and ID 11 is identical to ID 1 in all the *names.csv that I've found
> 
> I'm a native Japanese. You don't need to set romaji names.
> 
> ID 1 and 11 are not identical. ID 1 is ja, and ID 11 is ja without Kanji. In version names, they seem to be the same. However, flavor texts are different.

Ah I see. Thanks for the clarification.

**Review by Naramsim — APPROVED** [review]

**Comment by Naramsim** [comment]
Hi @giginet , would you like to become part of @pokeapi? We really appreciated your help in dumping data

**Comment by pokeapi-machine-user** [comment]
A [PokeAPI/api-data](https://github.com/PokeAPI/api-data) refresh has started. In 45 minutes the staging branch of [PokeAPI/api-data](https://github.com/PokeAPI/api-data/tree/staging) will be pushed with the new generated data. <br><br> The staging branch will be deployed in our [staging environment](https://staging.pokeapi.co/api/v2/) and you will be able to review the entire API. <br><br> A Pull Request ([master](https://github.com/PokeAPI/api-data/tree/master)<-[staging](https://github.com/PokeAPI/api-data/tree/staging)) will be also created at [PokeAPI/api-data](https://github.com/PokeAPI/api-data/pulls) and assigned to the PokeAPI Core team to be reviewed. If approved and merged new data will soon be available worldwide at [pokeapi.co](https://pokeapi.co/api/v2/).

**Comment by pokeapi-machine-user** [comment]
The updater script has finished its job and has now opened a Pull Request towards [PokeAPI/api-data](https://github.com/PokeAPI/api-data/pulls) with the updated data. <br><br> You can see the Pull Request deployed at our [staging environment](https://staging.pokeapi.co/api/v2/) when [CircleCI deploy](https://app.circleci.com/pipelines/github/PokeAPI/deploy) will be finished (_check the started time of the last build_).

**Comment by giginet** [comment]
@Naramsim I'm happy to hear about your offer. I can contribute to this repo.
I'm maintaining my product for future series. So I'm going to contribute to this repo to keep a sustainable data source.

**Pull request merged**
