### PR TITLE
Added missing sprites for pokemon ids 10064-10090.

### PR DESCRIPTION
**Pull request by smasher164**
fd9f0a5 Adds front images for the remaining 27 pokemon id's (10064 - 10090).
- PNG's are originally sourced from the [Smogon XY Sprite Project](http://www.smogon.com/forums/threads/xy-sprite-project-read-1st-post-the-face-of-the-metagame.3486712/), and [Project Pokemon](https://projectpokemon.org/)'s sprite dump.
- Resources were mainly discovered on [Deluge RPG](https://www.delugerpg.com).

### CODE REVIEW

**Comment by phalt** [comment]
NICE :+1:

**Comment by smasher164** [comment]
I've updated the branch to the latest revision. Just wondering if there are there any conflicts preventing this merge.
Thanks! 😃

**Comment by Gpx** [comment]
Is there any update on this issue?

**Comment by phalt** [comment]
@smasher164 @Gpx it's out of date again :( I'll be sure to merge it properly when it's updated next. Sorry!

**Comment by smasher164** [comment]
@phalt I apologize for the late response, I've updated the branch to the latest revision! Feel free to merge :)

**Pull request merged**
