### PR TITLE
Add french abilities translations

### PR DESCRIPTION
**Pull request by programgames**
Hello this is my first pr to this project : 
First of all https://www.pokepedia.fr/ is a very good french pokemon wiki website with accurate informations.
- ability_names.csv , I updated the name of one ability french name , as i changed since scarlet and violet : [french wiki](https://www.pokepedia.fr/Folle_Furie) + I removed a superfluous space in another one
- ability_flavor_text.csv : to make this, I scraped hundred of pokepedia wiki page to get most of flavor text for each generations.
As it lacked some of gen 9 data, i took them directely from the game rom file using PKNX. So i had to remove line breaks character from these one.
- ability_prose.csv, Here, as i understood, original data were scraped from veekun.com and are not dumped from the rom, So i simply translated them in french with OpenAi Api.
- pokemon_specy_names : Here, i scraped the genus from pokepedia.

### CODE REVIEW

**Comment by phalt** [comment]
First things first: congratulations on your first contribution. Well done!

Secondly: you've written your Pull Request description very well, good work. Context is key when proposing changes.

> ability_names.csv , I updated the name of one ability french name , as i changed since scarlet and violet : [french wiki](https://www.pokepedia.fr/Folle_Furie) + I removed a superfluous space in another one

Perfect.

> ability_flavor_text.csv : to make this, I scraped hundred of pokepedia wiki page to get most of flavor text for each generations.

A good approach.

> ability_prose.csv, Here, as i understood, original data were scraped from veekun.com and are not dumped from the rom, So i simply translated them in french with OpenAi Api.

I'm not sure what the precedent is for contributions translated this way. @Naramsim have we ever accepted anything like this before? Is there not an official source at all for this?

Everything else looks sensible.

**Comment by Naramsim** [comment]
Hi, about _ability_prose.csv_, the data was scraped (imported) from veekun that relied on ROM/trustworthy contributions. So the text present in the API and Veekun should reflect what's in the game. 

I think that using AI to translate English text to French is no good because it won't be the exact text found in the game. If a user would like to have this kind of information they can use AI in _their_ project and do the translation on their side. 

So, I would get rid of everything that's not effectively present in the Pokemon games.

**Comment by programgames** [comment]
Ok I removed the ability_prose file from this PR.
Actually I tried to understand how these strings were build in the old repo ( veekun ) . But I don't understood how it could come from the game directly when I watch some of these commits : 
https://github.com/veekun/pokedex/pull/181
https://github.com/veekun/pokedex/commit/d64090bd4ff26147608e566c47235374c76576d0
https://github.com/veekun/pokedex/pull/68/files
https://github.com/veekun/pokedex/pull/362/files
https://github.com/veekun/pokedex/compare/049fa143...7d5fbaec

Do you have an idea ? 
Anyway things like "[paralyze]{mechanic:paralysis}" seems to be a custom syntax used to create links / to the veekun website.

**Comment by Naramsim** [comment]
Yes, maybe we should get rid of those parentheses and clean up the data

**Comment by pokeapi-machine-user** [comment]
A [PokeAPI/api-data](https://github.com/PokeAPI/api-data) refresh has started. In ~45 minutes the staging branch of [PokeAPI/api-data](https://github.com/PokeAPI/api-data/tree/staging) will be pushed with the new generated data. <br><br> The staging branch will be deployed in our [staging environment](https://staging.pokeapi.co/api/v2/) and the entire API will be ready to review. <br><br> A Pull Request ([master](https://github.com/PokeAPI/api-data/tree/master)<-[staging](https://github.com/PokeAPI/api-data/tree/staging)) will be also created at [PokeAPI/api-data](https://github.com/PokeAPI/api-data/pulls) and assigned to the PokeAPI Core team to be reviewed. If approved and merged new data will soon be available worldwide at [pokeapi.co](https://pokeapi.co/api/v2/).

**Comment by pokeapi-machine-user** [comment]
The updater script has finished its job and has now opened a Pull Request towards [PokeAPI/api-data](https://github.com/PokeAPI/api-data/pulls) with the updated data. <br><br> The Pull Request can be seen deployed in our [staging environment](https://staging.pokeapi.co/api/v2/) when [CircleCI deploy](https://app.circleci.com/pipelines/github/PokeAPI/deploy) will be finished (_check the start time of the last build_).

**Pull request merged**
