### PR TITLE
updated README with Table Of Contents

### PR DESCRIPTION
**Pull request by 27Jashshah**
Added a Table of Contents, with clickable links to the sections, to the README file.

### CODE REVIEW

**Review by phalt — COMMENTED** [review]
This is a cool suggestion. Did you generate this with an auto-generator or do it yourself? Usually an autogenerated list wouldn't create the `<a>` tags because Github's markdown parser turns headings into links automatically.

**Comment by Naramsim** [comment]
Doctoc is one of the generators I used in the past. 

I don't know if we need a toc

**Comment by 27Jashshah** [comment]
So basically I was trying to add a toc with clickable links however it was not working for the top 5 sections for some reason, which is why I added the 'a' tags.

**Comment by phalt** [comment]
@27Jashshah what you can do is go to this readme on github.com, click each heading to see the correct link, like this one:

https://github.com/PokeAPI/pokeapi?tab=readme-ov-file#database-setup

the anchor you want is the part after the `#`

**Comment by raghav2005** [comment]
I definitely think that having a ToC makes the README a lot easier to navigate (and to see what's ahead in the README without having to explicitly scroll down), but yeah, there's no need to include the <a> tags cuz I'm pretty sure GitHub automatically handles jumping in Markdowns.

**Comment by 27Jashshah** [comment]
Ok, so the thing is, with the no-breaking spaces (&nbsp;), GitHub and Markdown files don't read the headers as they normally would (at least, to my knowledge), so the <a> tags are required for these ones. I have updated the code so that only the headers with the no-breaking space have the <a> tags - I'm just about to commit this change.

**Review by phalt — APPROVED** [review]
Nice work and thank you for the contribution!

**Comment by pokeapi-machine-user** [comment]
A [PokeAPI/api-data](https://github.com/PokeAPI/api-data) refresh has started. In ~45 minutes the staging branch of [PokeAPI/api-data](https://github.com/PokeAPI/api-data/tree/staging) will be pushed with the new generated data. <br><br> The staging branch will be deployed in our [staging environment](https://staging.pokeapi.co/api/v2/) and the entire API will be ready to review. <br><br> A Pull Request ([master](https://github.com/PokeAPI/api-data/tree/master)<-[staging](https://github.com/PokeAPI/api-data/tree/staging)) will be also created at [PokeAPI/api-data](https://github.com/PokeAPI/api-data/pulls) and assigned to the PokeAPI Core team to be reviewed. If approved and merged new data will soon be available worldwide at [pokeapi.co](https://pokeapi.co/api/v2/).

**Comment by pokeapi-machine-user** [comment]
The updater script has finished its job and has now opened a Pull Request towards [PokeAPI/api-data](https://github.com/PokeAPI/api-data/pulls) with the updated data. <br><br> The Pull Request can be seen deployed in our [staging environment](https://staging.pokeapi.co/api/v2/) when [CircleCI deploy](https://app.circleci.com/pipelines/github/PokeAPI/deploy) will be finished (_check the start time of the last build_).

**Pull request merged**
