### PR TITLE
Sync data from `PokeAPI/pokedex`

### PR DESCRIPTION
**Pull request by Naramsim**
Most of the new data is from @myoKun345 (https://github.com/PokeAPI/pokedex/pull/17), @alex-whan (https://github.com/PokeAPI/pokedex/pull/14) and @Amaterasu5 plus some [leftovers](https://bulbapedia.bulbagarden.net/wiki/Leftovers) I forgot.

Deployed here: https://staging.pokeapi.co/api/v2/pokemon?offset=0&limit=2000000000

@myoKun345 and @alex-whan, could you check your changes?

Thanks a lot for this final effort 🥇

### CODE REVIEW

**Comment by alex-whan** [comment]
> Most of the new data is from @myoKun345 ([PokeAPI/pokedex#17](https://github.com/PokeAPI/pokedex/pull/17)), @alex-whan ([PokeAPI/pokedex#14](https://github.com/PokeAPI/pokedex/pull/14)) and @Amaterasu5 plus some [leftovers](https://bulbapedia.bulbagarden.net/wiki/Leftovers) I forgot.
> 
> Deployed here: https://staging.pokeapi.co/api/v2/pokemon?offset=0&limit=2000000000
> 
> @myoKun345 and @alex-whan, could you check your changes?
> 
> Thanks a lot for this final effort 🥇

Hi @Naramsim, great! All of my information looks good. I'll leave a review confirming this, as well.

**Review by alex-whan — COMMENTED** [review]
Hi @Naramsim, I can confirm that all of the changes/data I added look to be correct.

**Review by alex-whan — APPROVED** [review]
Hi @Naramsim, I can confirm that all of the changes/data I added look to be correct.

**Review by myoKun345 — APPROVED** [review]

**Comment by pokeapi-machine-user** [comment]
A [PokeAPI/api-data](https://github.com/PokeAPI/api-data) refresh has started. In 45 minutes the staging branch of [PokeAPI/api-data](https://github.com/PokeAPI/api-data/tree/staging) will be pushed with the new generated data. <br><br> The staging branch will be deployed in our [staging environment](https://staging.pokeapi.co/api/v2/) and you will be able to review the entire API. <br><br> A Pull Request ([master](https://github.com/PokeAPI/api-data/tree/master)<-[staging](https://github.com/PokeAPI/api-data/tree/staging)) will be also created at [PokeAPI/api-data](https://github.com/PokeAPI/api-data/pulls) and assigned to the PokeAPI Core team to be reviewed. If approved and merged new data will soon be available worldwide at [pokeapi.co](https://pokeapi.co/api/v2/).

**Comment by pokeapi-machine-user** [comment]
The updater script has finished its job and has now opened a Pull Request towards [PokeAPI/api-data](https://github.com/PokeAPI/api-data/pulls) with the updated data. <br><br> You can see the Pull Request deployed at our [staging environment](https://staging.pokeapi.co/api/v2/) when [CircleCI deploy](https://app.circleci.com/pipelines/github/PokeAPI/deploy) will be finished (_check the started time of the last build_).

**Pull request merged**
