### PR TITLE
Fixed Docker Postgres Config

### PR DESCRIPTION
**Pull request by ZSGaming1998**

### CODE REVIEW

**Comment by Naramsim** [comment]
Was it broken?

As far that I know Compose allows both ways.

**Comment by ZSGaming1998** [comment]
i couldn't get it to dock on my instance without these setting using latest
of everything

**Comment by phalt** [comment]
That's a pretty significant syntax change?

**Comment by phalt** [comment]
Looks to be correct though: https://docs.docker.com/compose/environment-variables/#set-environment-variables-in-containers

**Comment by ZSGaming1998** [comment]
yes i agree it took me awhile to figure out what was wrong. until i found the syntax change.

**Comment by ZSGaming1998** [comment]
Idk it your repo that was my solution i could not get it to work im on a new windows install everything is up to date if theres any problems here you guys go keep up the good work!

**Comment by Naramsim** [comment]
Hi @ZSGaming1998,

I checked both for Compose 2 and Compose 3, the syntax we use is still correct.

https://docs.docker.com/compose/compose-file/compose-file-v3/#environment

Can you tell me the version of your `docker-compose`? Is it 3.9?

**Comment by Naramsim** [comment]
Closing due to inactivity and unnecessity

**Pull request closed without merging**
