### PR TITLE
Implemented suggest change of renaming locations.csv id=768 to malie-city--proper

### PR DESCRIPTION
**Pull request by O-Tahmas**
This PR addresses the issue of duplicate location entries in `locations.csv` for `malie-city`. Currently, both id=768 and id=1045 are listed as malie-city. To resolve this, id=768 has been renamed to `malie-city--proper`.

This change ensures that all (region_id, identifier) combinations in locations.csv are unique, maintaining data integrity and clarity for location entries.

### CODE REVIEW

**Comment by Naramsim** [comment]
Hi! Why the double `--`?

**Comment by O-Tahmas** [comment]
> Hi! Why the double `--`?

Hey!
I just copied & pasted from the issue thread to be safe :) 
https://github.com/PokeAPI/pokeapi/issues/1097

**Comment by Naramsim** [comment]
Yeah, but that's not a valid reason 😂😂. 

I'd say we go with the single one. Or maybe you can tag the guy who replied to you on the other issues

**Comment by Naramsim** [comment]
Hi @O-Tahmas , can you remove one dash so we can merge?

**Review by Naramsim — APPROVED** [review]

**Comment by pokeapi-machine-user** [comment]
A [PokeAPI/api-data](https://github.com/PokeAPI/api-data) refresh has started. In ~45 minutes the staging branch of [PokeAPI/api-data](https://github.com/PokeAPI/api-data/tree/staging) will be pushed with the new generated data. <br><br> The staging branch will be deployed in our [staging environment](https://staging.pokeapi.co/api/v2/) and the entire API will be ready to review. <br><br> A Pull Request ([master](https://github.com/PokeAPI/api-data/tree/master)<-[staging](https://github.com/PokeAPI/api-data/tree/staging)) will be also created at [PokeAPI/api-data](https://github.com/PokeAPI/api-data/pulls) and assigned to the PokeAPI Core team to be reviewed. If approved and merged new data will soon be available worldwide at [pokeapi.co](https://pokeapi.co/api/v2/).

**Comment by pokeapi-machine-user** [comment]
The updater script has finished its job and has now opened a Pull Request towards [PokeAPI/api-data](https://github.com/PokeAPI/api-data/pulls) with the updated data. <br><br> The Pull Request can be seen deployed in our [staging environment](https://staging.pokeapi.co/api/v2/) when [CircleCI deploy](https://app.circleci.com/pipelines/github/PokeAPI/deploy) will be finished (_check the start time of the last build_).

**Pull request merged**
