### PR TITLE
chore(data): added some gen 8 data.

### PR DESCRIPTION
**Pull request by Crash2490**
Added Meltan and Melmetal, along with their types. Added missing types for pokemon from 808 - 893.
Manually entered data from Bulbapedia. One pokemon: #892 Urshifu, has two different forms. I wasn't sure how to enter this information, so I have only entered the type info for the fighting/dark form.

### CODE REVIEW

**Comment by Naramsim** [comment]
Hi Thanks for the PR!  How did you compile the types? Manually or using a script?

**Comment by phalt** [comment]
This isn't far off what I did for the original data back in 2014 so that should be okay.

**Comment by Naramsim** [comment]
Alright! I've checked some of them and they are ok. I'll transfer this data also to our `veekun/pokedex`.

**Review by Naramsim — APPROVED** [review]

**Comment by pokeapi-machine-user** [comment]
A [PokeAPI/api-data](https://github.com/PokeAPI/api-data) refresh has started. In 45 minutes the staging branch of [PokeAPI/api-data](https://github.com/PokeAPI/api-data/tree/staging) will be pushed with the new generated data. <br><br> The staging branch will be deployed in our [staging environment](https://staging.pokeapi.co/api/v2/) and you will be able to review the entire API. <br><br> A Pull Request ([master](https://github.com/PokeAPI/api-data/tree/master)<-[staging](https://github.com/PokeAPI/api-data/tree/staging)) will be also created at [PokeAPI/api-data](https://github.com/PokeAPI/api-data/pulls) and assigned to the PokeAPI Core team to be reviewed. If approved and merged new data will soon be available worldwide at [pokeapi.co](https://pokeapi.co/api/v2/).

**Pull request merged**
