### PR TITLE
Add types field to PokemonForm model

### PR DESCRIPTION
**Pull request by phrasmotica**
These changes add a `types` field to the PokemonForm model. This field is identical to the `types` field on the Pokemon model, except it is an empty list if the Pokemon form shares its types with its parent Pokemon.

```
"types": [
    {
        "slot": 1,
        "type": {
            "name": "bug",
            "url": "https://pokeapi.co/api/v2/type/7/"
        }
    }
]
```

Type data has been added for the non-default forms of Arceus and Silvally. The CSV file containing the data has entries containing the Pokemon form's ID, the type and its slot.

The API README file has been updated with an explanation of the new data and example JSON from Arceus' Bug form.

Data derived from the existing data in PokeAPI and https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_with_form_differences.

### CODE REVIEW

**Comment by phrasmotica** [comment]
I realise I should've opened an issue before creating this PR, apologies. But hopefully this data can be usefu!

**Comment by Naramsim** [comment]
Hi @phrasmotica,

from my understanding (I didn't test anything) you are populating the contents of the newly created `types` with the type of the form only if it's not the same as the parent pokemon.

In my opinion, this is counter-intuitive. The new field `types` should always be populated and in most cases, it will be populated with the same type of the parent pokemon, since most of the time forms don't have a type change.

**Comment by Naramsim** [comment]
@phrasmotica bump :)

**Comment by phrasmotica** [comment]
@Naramsim I'm not against always populating the form types field. And I agree, the convenience of having the types already there is probably worth the data duplication since it saves a subsequent request to get the types from the parent Pokemon resource.

I can make the required changes - for the Pokemon forms with the same types as their parent Pokemon, I guess we can read that data from `pokemon_types.csv`?

**Comment by Naramsim** [comment]
Yeah, that should be the same file used to populate the `types` for the `/pokemon/{id}` endpoint.

**Comment by phrasmotica** [comment]
@Naramsim I've made the changes as discussed 😃

**Comment by phrasmotica** [comment]
@Naramsim bump 😃

**Review by Naramsim — APPROVED** [review]

**Comment by pokeapi-machine-user** [comment]
A [PokeAPI/api-data](https://github.com/PokeAPI/api-data) refresh has started. In 45 minutes the staging branch of [PokeAPI/api-data](https://github.com/PokeAPI/api-data/tree/staging) will be pushed with the new generated data. <br><br> The staging branch will be deployed in our [staging environment](https://staging.pokeapi.co/api/v2/) and you will be able to review the entire API. <br><br> A Pull Request ([master](https://github.com/PokeAPI/api-data/tree/master)<-[staging](https://github.com/PokeAPI/api-data/tree/staging)) will be also created at [PokeAPI/api-data](https://github.com/PokeAPI/api-data/pulls) and assigned to the PokeAPI Core team to be reviewed. If approved and merged new data will soon be available worldwide at [pokeapi.co](https://pokeapi.co/api/v2/).

**Comment by pokeapi-machine-user** [comment]
The updater script has finished its job and has now opened a Pull Request towards [PokeAPI/api-data](https://github.com/PokeAPI/api-data/pulls) with the updated data. <br><br> You can see the Pull Request deployed at our [staging environment](https://staging.pokeapi.co/api/v2/) when [CircleCI deploy](https://app.circleci.com/pipelines/github/PokeAPI/deploy) will be finished (_check the started time of the last build_).

**Pull request merged**
