### PR TITLE
New PHP Wrapper, with lazy-loading and POPOs

### PR DESCRIPTION
**Pull request by lmerotta**

### CODE REVIEW

**Comment by Naramsim** [comment]
Hi, 
thanks for this wrapper! It looks awesome, I also suggest you to modify our readme to include it. Meanwhile you could add some tests to your module :wink:, that would be awesome.

**Comment by lmerotta** [comment]
Hi,
Thanks for the feedback ! Tests are on their way 😄 Should I add the wrapper in the official wrappers section ?

**Comment by Naramsim** [comment]
Maybe you can add it when you finish the missing endpoints (Contests, Pokéathlons). Is there a specific reason for why you left them out?

**Comment by lmerotta** [comment]
They are under development actually, I released the wrapper because it was complete enough to be published. The missing endpoints will be added in the 1.1.0 release in the following days.

Maybe we can leave this pull request open, and I’ll update it once the wrapper hits 1.1.0, are you okay with this ?

**Comment by Naramsim** [comment]
I think we could wait a second for @tdmalone, I really trust him on PHP development.

I really like the structure of your wrapper and the _proxy_ function.

**Pull request merged**
