### PR TITLE
Johto Safari Zone, fix encounters/methods, roaming Pokemon and new encounters

### PR DESCRIPTION
**Pull request by SimplyBLGDev**
After much research I was able to find out some mechanics from the johto safari zone, it uses completely different encounter slots in walking, surfing, old rod, good rod and super rod, I was able to determine that it's 10 walk slots all have a 10% chance but wasn't so lucky in finding the chance for the surfing, old rod, good rod and super rod 12 slots, I have -some- confidence that it has 10 10% chance slots and 2 0% chance slots, if more info comes to light about these slots I'll update this info at another time.

+ Added Johto Safari Zone location
+ Added all 12 Safari Zone areas
+ Added all 2880 encounters from the safari zone (For both HG and SS)

### CODE REVIEW

**Comment by SimplyBLGDev** [comment]
You can find the tool I made to generate all these rows [in this gist](https://gist.github.com/SimplyBLGDev/5d23f6bdb0727c157b8eb996d060c34c).

In another time I'll add the missing event Pokemon encounters for gens 4 and 5 (I'll make another PR for that in the future)

**Comment by SimplyBLGDev** [comment]
It also is important to note that these are the regular encounters for the safari zone areas and does not include the block encounters, I'll add those at a later date, although that may require some new data structures due to the uniqueness of the mechanic.

**Comment by SimplyBLGDev** [comment]
#737 Is solved with my original commit
I've also added some missing conditions in crystal route 13, as reported #735

**Comment by SimplyBLGDev** [comment]
@Naramsim Ok, I'm done, this is ready to be merged

**Comment by SimplyBLGDev** [comment]
Something to be noted is that I was about to fix the unown encounters in FR/LG, HG/SS, D/P and Pt but unown forms aren't listed with the other alternative forms in the pokemon table for some reason, I'd add them but I need your OK to do so @Naramsim

**Comment by SimplyBLGDev** [comment]
This is a pretty big commit but it's ready to be merged, one of my websites uses the encounter data so if it could be reviewed soon that would be great.

Still missing:
+ Gen 5, 6, 7 & 8 static, legendary and event Pokémon encounters
+ Bug catching contest slots and encounters (It works differently than most encounters and the safari zone, these mechanics haven't been decompiled yet so it requires some extra research)
+ Separate missing alternate form Pokemon to the Pokemon table (So that they can be referenced in the encounters)
+ Update alternate forms encounters for these Pokémon (Most notably Shellos, Gastrodon, Burmy, Wormadam and Unown) in appropriate games.

**Comment by SimplyBLGDev** [comment]
Paging @Naramsim can we merge these changes?

**Comment by Naramsim** [comment]
@SimplyBLGDev I'm sooooo sorry!!! please excuse me! I got your email in my spam folder! Thanks for pinging me there! I'll merge the PR. I didn't really review it, but I see it only adds CSV data so I think we are fine with it. 

Maybe you can test the staging env later.

**Review by Naramsim — APPROVED** [review]

**Comment by pokeapi-machine-user** [comment]
A [PokeAPI/api-data](https://github.com/PokeAPI/api-data) refresh has started. In 45 minutes the staging branch of [PokeAPI/api-data](https://github.com/PokeAPI/api-data/tree/staging) will be pushed with the new generated data. <br><br> The staging branch will be deployed in our [staging environment](https://staging.pokeapi.co/api/v2/) and you will be able to review the entire API. <br><br> A Pull Request ([master](https://github.com/PokeAPI/api-data/tree/master)<-[staging](https://github.com/PokeAPI/api-data/tree/staging)) will be also created at [PokeAPI/api-data](https://github.com/PokeAPI/api-data/pulls) and assigned to the PokeAPI Core team to be reviewed. If approved and merged new data will soon be available worldwide at [pokeapi.co](https://pokeapi.co/api/v2/).

**Comment by pokeapi-machine-user** [comment]
The updater script has finished its job and has now opened a Pull Request towards [PokeAPI/api-data](https://github.com/PokeAPI/api-data/pulls) with the updated data. <br><br> You can see the Pull Request deployed at our [staging environment](https://staging.pokeapi.co/api/v2/) when [CircleCI deploy](https://app.circleci.com/pipelines/github/PokeAPI/deploy) will be finished (_check the started time of the last build_).

**Comment by Naramsim** [comment]
@SimplyBLGDev , can you test on https://staging.pokeapi.co/api/v2/

**Comment by SimplyBLGDev** [comment]
> @SimplyBLGDev , can you test on https://staging.pokeapi.co/api/v2/

I can see the new data, seems to be correct at first glance.

**Comment by Naramsim** [comment]
Ok, I merge

**Pull request merged**
