### PR TITLE
Fix scrubbing for rare cases

### PR DESCRIPTION
**Pull request by Naramsim**
https://github.com/veekun/pokedex/pull/291
https://github.com/veekun/pokedex/pull/290

To be merged after https://github.com/PokeAPI/pokeapi/pull/464

### CODE REVIEW

**Comment by Naramsim** [comment]
Reviews were automatically dismissed when I resolved some conflicts.

**Comment by Naramsim** [comment]
@Kronopt, @tasadurian hello!

I don't have your emails so I text you here. I just spoke with @phalt and @tdmalone about promoting you to have write-access to this repository so that we can collaborate and get these PRs merged :) I think the two of you are quite active on Github and you also care about our project. 

If it's fine for you I'll 'promote' you. Let me know in a comment below.

Thanks!!

**Comment by tasadurian** [comment]
@Naramsim sounds good

**Comment by Kronopt** [comment]
I'm fine with it! 👍

**Pull request merged**
