### PR TITLE
Corrected en-us growth rate names

### PR DESCRIPTION
**Pull request by DDriggs00**
Previously, the names for the `erratic` and `fluctuating` en-us growth rates were listed incorrectly.

Note that Language id 6 (German) also needs corrected by someone who speaks German.

### CODE REVIEW

**Comment by Naramsim** [comment]
Thanks for this PR. I see that the names have changed. Would you be so kind to open the same PR or better an issue over at `veekun/pokedex` and check what the guys (@magical) say? Maybe the names we are currently using are for past generations. 

If we end up accepting your contribution. Maybe it's worth changing the https://github.com/PokeAPI/pokeapi/blob/master/data/v2/csv/growth_rates.csv file as well. (And check the formulas to be still correct)

**Comment by DDriggs00** [comment]
I created a pull request, but that repo appears unmaintained

**Comment by helblingjoel** [comment]
> Note that Language id 6 (German) also needs corrected by someone who speaks German.

Is this still required? I'd be happy to do that tomorrow?

**Comment by Naramsim** [comment]
@helblingjoel I just merged the PR, if you like you could update the german names and open a new one

**Comment by pokeapi-machine-user** [comment]
A [PokeAPI/api-data](https://github.com/PokeAPI/api-data) refresh has started. In 45 minutes the staging branch of [PokeAPI/api-data](https://github.com/PokeAPI/api-data/tree/staging) will be pushed with the new generated data. <br><br> The staging branch will be deployed in our [staging environment](https://staging.pokeapi.co/api/v2/) and you will be able to review the entire API. <br><br> A Pull Request ([master](https://github.com/PokeAPI/api-data/tree/master)<-[staging](https://github.com/PokeAPI/api-data/tree/staging)) will be also created at [PokeAPI/api-data](https://github.com/PokeAPI/api-data/pulls) and assigned to the PokeAPI Core team to be reviewed. If approved and merged new data will soon be available worldwide at [pokeapi.co](https://pokeapi.co/api/v2/).

**Comment by pokeapi-machine-user** [comment]
The updater script has finished its job and has now opened a Pull Request towards [PokeAPI/api-data](https://github.com/PokeAPI/api-data/pulls) with the updated data. <br><br> You can see the Pull Request deployed at our [staging environment](https://staging.pokeapi.co/api/v2/) when [CircleCI deploy](https://app.circleci.com/pipelines/github/PokeAPI/deploy) will be finished (_check the started time of the last build_).

**Pull request merged**
