### PR TITLE
Fix duplicated model name in docsv2 document

### PR DESCRIPTION
**Pull request by relrod**
Apparently writing a thing to parse the models/types into Haskell data types is a good way to find this kind of stuff ;)

### CODE REVIEW

**Comment by relrod** [comment]
Oops, the previous PR got undone here, one sec

**Comment by relrod** [comment]
@phalt ok, good to go. Sorry, I was trying to be a cool kid and edit with the GitHub editor instead of being sane and using the git cli. It didn't work out too well. :P

**Comment by sargunster** [comment]
:+1: 

Do you mind fixing the "list [PokemonSpeciesVariety]" link a few lines up too? It's at the bottom of the PokemonSpecies table.

**Comment by relrod** [comment]
Done!

**Pull request merged**
