### PR TITLE
docs(openapi): `q` query string param, fix `id` path parameter, nix refactor

### PR DESCRIPTION
**Pull request by Indyandie**
# OpenAPI Docs

- `q` query string param
- fix `id` path parameter
- nix refactor

Related #1078 #1065

### CODE REVIEW

**Comment by Indyandie** [comment]
@Naramsim

**Comment by Naramsim** [comment]
Hi, when trying your schema here: https://editor-next.swagger.io/

I don't see the `q` parameter for `/abilities/`, is it missing somewhere? On the other hand, if I check out `/berries/` I have `q` but it's weirdly formatted:
swagger

Also, I don't really like the fat that we are adding other code to every method just for documenting one querystring. Can't we treat `q` like `offset` or `limit`?

**Comment by Indyandie** [comment]
I'll take a look and try to figure how to apply it like `offset` and `limit`. Where are those defined? Sorry i am not too familiar with django... 😅

**Comment by Indyandie** [comment]
@Naramsim I got rid of all that unnecessary code. All the endpoints that use `PokeapiCommonViewset` should pick up the definitions. The formatting is probably that swagger isn't reading the `quoteblock` properly.

**Comment by Naramsim** [comment]
Nice! Thanks a lot! If you have time, would you be able to fix the quoteblock strange formatting? Also, in the console I see other errors and warnings. 

Many thanks!

**Comment by pokeapi-machine-user** [comment]
This Pull Request won't be deployed since the label `no-deploy` was found in its meta-data.

**Comment by Indyandie** [comment]
> Nice! Thanks a lot! If you have time, would you be able to fix the quoteblock strange formatting? Also, in the console I see other errors and warnings.
> 
> Many thanks!

@Naramsim what command is generating the errors and warnings, can you share them? Or can you create an issue with all the details?

**Comment by Naramsim** [comment]
If you go [here](https://editor-next.swagger.io/) and input your openapi URL and then wait 15 seconds, a popup opens up in the bottom part and you can see something like:



Severity | Line | Code | Message
-- | -- | -- | --
  | 9320 | 7010601 | tags must be an array of Tag Objects
  | 2795 | 10069 | property "example" is deprecated, use "examples" instead

**Pull request merged**
