### PR TITLE
Add move names for LGPE

### PR DESCRIPTION
**Pull request by AndreArrebola**
Info taken from Bulbapedia:
https://bulbapedia.bulbagarden.net/wiki/List_of_moves_in_other_languages

### CODE REVIEW

**Comment by Naramsim** [comment]
Yep, we only have moves up to 728 in pokeapi. No need to add the ones past 728, otherwise the app breaks. Could you please truncate them?

**Comment by Naramsim** [comment]
😞 I only realized we already have the moves translated up to ID 728. So we cannot merge your PR up until we will add the new moves themselves in the `moves.csv` file.

**Comment by AndreArrebola** [comment]
Hmm, Let me try adding the move data too then

**Comment by Naramsim** [comment]
> Hmm, I'll try adding the move data too then

If you do, please use a script. It's nonsense to do it manually.

If you do, you can start from these scripts: https://github.com/PokeAPI/pokedex/tree/master-pokeapi/pokeapi/scripts/scraper_node

Personally, I'd scrape bulbapedia this way:

Here a JSON of moves and their IDs

```json
{
    "Zippy Zap": 729,
    "Splishy Splash": 730,
    "Floaty Fall": 731,
    "Pika Papow": 732,
    "Bouncy Bubble": 733,
    "Buzzy Buzz": 734,
    "Sizzly Slide": 735,
    "Glitzy Glow": 736,
    "Baddy Bad": 737,
    "Sappy Seed": 738,
    "Freezy Frost": 739,
    "Sparkly Swirl": 740,
    "Veevee Volley": 741,
    "Double Iron Bash": 742,
    "Max Guard": 743,
    "Dynamax Cannon": 744,
    "Snipe Shot": 745,
    "Jaw Lock": 746,
    "Stuff Cheeks": 747,
    "No Retreat": 748,
    "Tar Shot": 749,
    "Magic Powder": 750,
    "Dragon Darts": 751,
    "Teatime": 752,
    "Octolock": 753,
    "Bolt Beak": 754,
    "Fishious Rend": 755,
    "Court Change": 756,
    "Max Flare": 757,
    "Max Flutterby": 758,
    "Max Lightning": 759,
    "Max Strike": 760,
    "Max Knuckle": 761,
    "Max Phantasm": 762,
    "Max Hailstorm": 763,
    "Max Ooze": 764,
    "Max Geyser": 765,
    "Max Airstream": 766,
    "Max Starfall": 767,
    "Max Wyrmwind": 768,
    "Max Mindstorm": 769,
    "Max Rockfall": 770,
    "Max Quake": 771,
    "Max Darkness": 772,
    "Max Overgrowth": 773,
    "Max Steelspike": 774,
    "Clangorous Soul": 775,
    "Body Press": 776,
    "Decorate": 777,
    "Drum Beating": 778,
    "Snap Trap": 779,
    "Pyro Ball": 780,
    "Behemoth Blade": 781,
    "Behemoth Bash": 782,
    "Aura Wheel": 782,
    "Breaking Swipe": 784,
    "Branch Poke": 785,
    "Overdrive": 786,
    "Apple Acid": 787,
    "Grav Apple": 788,
    "Spirit Break": 789,
    "Strange Steam": 790,
    "Life Dew": 791,
    "Obstruct": 792,
    "False Surrender": 793,
    "Meteor Assault": 794,
    "Eternabeam": 795,
    "Steel Beam": 796
}
```

Use the key to make calls to https://bulbapedia.bulbagarden.net/wiki/Zing_Zap_(move). Just substitute the spaces with `_`.

Then build the `moves.csv` file

**Comment by AndreArrebola** [comment]
Hmm, I added info manually in the previous commit, but will try to make a script instead then and add remaining attacks. Thanks for sending me the script link, it looks very useful!

**Comment by AndreArrebola** [comment]
Added the commit in this repo too, please tell me if something goes wrong during merging.

**Comment by Naramsim** [comment]
Hi @AndreArrebola, I successfully deployed it in `staging`.

Could you double-check some values to see if they are correct?

https://staging.pokeapi.co/api/v2/move/796/

**Comment by AndreArrebola** [comment]
Hello! Sorry for the wait, the last few days were a bit busy.
It apparently looks fine, the values are right

**Pull request merged**
