### PR TITLE
Added Follow-Me to Squirtle, Pichu, Magmar

### PR DESCRIPTION
**Pull request by linnos**
These 3 pokemon(Squirtle, Pichu, Magmar) were missing the move Follow-Me. Added it to their move sets.
To test: Load up one of the 3 pokemon, check to make sure their moves include follow-me.

### CODE REVIEW

**Comment by pokeapi-machine-user** [comment]
A [PokeAPI/api-data](https://github.com/PokeAPI/api-data) refresh has started. In 45 minutes the staging branch of [PokeAPI/api-data](https://github.com/PokeAPI/api-data/tree/staging) will be pushed with the new generated data. <br><br> The staging branch will be deployed in our [staging environment](https://staging.pokeapi.co/api/v2/) and you will be able to review the entire API. <br><br> A Pull Request ([master](https://github.com/PokeAPI/api-data/tree/master)<-[staging](https://github.com/PokeAPI/api-data/tree/staging)) will be also created at [PokeAPI/api-data](https://github.com/PokeAPI/api-data/pulls) and assigned to the PokeAPI Core team to be reviewed. If approved and merged new data will soon be available worldwide at [pokeapi.co](https://pokeapi.co/api/v2/).

**Comment by pokeapi-machine-user** [comment]
The updater script has finished its job and has now opened a Pull Request towards [PokeAPI/api-data](https://github.com/PokeAPI/api-data/pulls) with the updated data. <br><br> You can see the Pull Request deployed at our [staging environment](https://staging.pokeapi.co/api/v2/) when [CircleCI deploy](https://app.circleci.com/pipelines/github/PokeAPI/deploy) will be finished (_check the started time of the last build_).

**Comment by Naramsim** [comment]
Hi, can you provide evidence that they learn that move? We have a PR that reverts your contribution

**Comment by linnos** [comment]
> Hi, can you provide evidence that they learn that move? We have a PR that reverts your contribution

Yes. https://bulbapedia.bulbagarden.net/wiki/Follow_Me_(move)
According to this page
* Squirtle: Gen 5 from Sticker promotional Egg Squirtle and Kanto First Partner Egg Squirtle
* Pichu: Gen 3 PokePark Eggs
* Magmar: Gen 3 Purified Shadow Pokemon. Also learned by pre-evolution Magby by breeding.

**Comment by Naramsim** [comment]
Thanks for the reply, could you then chime in here https://github.com/PokeAPI/pokeapi/pull/1415#pullrequestreview-3819948244

I think we need to revise this data

Thanks!

**Pull request merged**
