### PR TITLE
Meltan, Melmetal, Double Iron Bash move and Let's Go Eevee and Let's Go Pikachu version groups

### PR DESCRIPTION
**Pull request by ks129**
Like title say... all of these added. Used #466 branch.

### CODE REVIEW

**Comment by Naramsim** [comment]
Thanks a lot for the hard work @ks129, I saw you also opened a PR towards veekun/pokedex, that the right thing! :) Let's see if one of their maintainers comes back at us and approves the PR over there. If so I would be happy to merge your contribution!

If they don't come back maybe we could fork veekun/pokedex to our organization and merge your contribs there. And then we could simply use the forked data. Let's give Veekun at least one or two weeks.

**Comment by ks129** [comment]
@Naramsim One note: Veekun changes is little bit different, due there I didn't added new body shapes and habitats (unknown), due this built successfully without these, but PokeAPI building gave error when these values was empty.

**Comment by Naramsim** [comment]
Ok, good to know, do you think is possible to have the same data here and there? Maybe by changing a bit our code and handling the build error?

**Comment by ks129** [comment]
@Naramsim now should all changes same here and there

**Comment by phalt** [comment]
There are conflicts now against the master branch.

Can we link the veekun issue related to this here so we can track it?

**Comment by Naramsim** [comment]
PR opened over veekun/pokedex: https://github.com/veekun/pokedex/pull/292

**Comment by Naramsim** [comment]
The conflicts are trivial to fix

**Comment by Naramsim** [comment]
Hi @ks129, sorry for coming back after such a long time, but as you've seen Veekun didn't want to merge your data. We recently created a fork of Veekun at https://github.com/PokeAPI/pokedex. 

If you are still interested in bringing in your changes to PokeAPI, could you please open a PR over there with the new data and then a new clean one here?

Thanks a lot!!

**Comment by Naramsim** [comment]
Closing since we merged other PRs that brought in the same data.

**Pull request closed without merging**
