### PR TITLE
data in some languages(Korean, Japanese, French, German) added a little bit.

### PR DESCRIPTION
**Pull request by ymin1103**
I made a small data contribution in some languages : Korean(especially), Japanese, French, German.

- version_names : Korean, French, German, Japanese

- generation_names : Korean

- stat_names : Korean

- egg_groups : Korean

- location_names : Korean

### CODE REVIEW

**Comment by cmmartti** [comment]
We take our CSV data directly from [Veekun](https://github.com/Veekun/pokedex) without modifying it, so please direct any translations, etc. to them. If they're merged there, those changes will make their way into PokéAPI. Do you know Korean, French, German, and Japanese yourself? If not, where are the translations from?

**Comment by ymin1103** [comment]
Ok, sorry for my ignorance. So do I have to make contribution at Veekun when it comes to translation, etc? 
I know Korean, English, Japanese. French and German translated data were from some wikipedias about pokemon  (ie. bulbapedia)

**Comment by cmmartti** [comment]
Yes, exactly. They'll want to know that the translations are accurate, which is why I asked.

**Comment by ymin1103** [comment]
Thank you for your kindness. 😀

**Pull request closed without merging**
