### PR TITLE
Fixed wrong ids of pokemons from Scarlet and Violet games

### PR DESCRIPTION
**Pull request by tillfox**
Fixed wrong ids for all Pokemons from Scarlet and Violet in the following relations:

- encounters (pokemon_id)
- pokemon (id, species_id)*
- pokemon_abilities (pokemon_id)
- pokemon_form_generations (pokemon_form_id)
- pokemon_form_names (pokemon_form_id)
- pokemon_forms (id, pokemon_id)*
- pokemon_species (id, evolves_from_species_id)*
- pokemon_species_flavor_text (species_id)
- pokemon_species_names (pokemon_species_id)*
- pokemon_stats (pokemon_id)
- pokemon_types (pokemon_id)
- pokemon_evolution

A little side effect, that doesn't ruin integrity of data (It could be seen as an improvement actually), is that some tuples have been re-ordered according to numerical ascending order (for example on slot_id, language_id, etc.)

### CODE REVIEW

**Comment by Naramsim** [comment]
Hi @tillfox many thanks for the PR!!! 

When building pokemon_v2_pokemonmove I get the error: DETAIL:  Key (pokemon_id)=(1009) is not present in table "pokemon_v2_pokemon".

So in the `pokemon_moves.csv` file it seems the `id`s didn't get updated.

**Comment by tillfox** [comment]
The last commit should fix the problem, but if you wait I can find a way to fix it even better, ordering tuples from pokemon_moves.csv, which is really a mess by now @Naramsim

**Comment by tillfox** [comment]
Ok, @Naramsim it took a while, because the file pokemon_moves.csv is huge, but I successfully fixed the wrong ids and sorted the lines in ascending order

**Comment by Naramsim** [comment]
Ok, perfect! I just finished the test on your previous commit and it build fine. I'll re-test and then merge

**Comment by pokeapi-machine-user** [comment]
The updater script has finished its job and has now opened a Pull Request towards [PokeAPI/api-data](https://github.com/PokeAPI/api-data/pulls) with the updated data. <br><br> You can see the Pull Request deployed at our [staging environment](https://staging.pokeapi.co/api/v2/) when [CircleCI deploy](https://app.circleci.com/pipelines/github/PokeAPI/deploy) will be finished (_check the started time of the last build_).

**Pull request merged**
