### PR TITLE
Added all Alcremie forms

### PR DESCRIPTION
**Pull request by rayusagi**
Relates to issue #1069.

There already was 7 forms of Alcremie but they didn't take into account the sweet type. Consequently, I renamed these 7 existing forms to match the new pattern of `alcremie-[type-of-cream]-[type-of-sweet]`.

I then added the missing 56 forms of Alcremie with proper form names for both english and french languages.  
At the same time, I created a PR on the sprites project to match these new form names: https://github.com/PokeAPI/sprites/pull/154

Regarding the order of these new forms in the CSV file, I wasn't sure if it was needed to bump all the following forms in order to insert these new forms so I didn't. I assumed it would be OK to consider that all 7 Alcremie forms of a given type of cream could share the same order.
Let me know if it's not a good idea and if we do need to bump the order of all the following forms.

### CODE REVIEW

**Comment by Naramsim** [comment]
Hi! Thanks for the PR. I ping @JRuffs7, he created an issue for this in the past (https://github.com/PokeAPI/pokeapi/issues/1069). And also @Deleca7755 that left a comment there. I hope they can help us with this PR.

**Comment by Deleca7755** [comment]
It seems fine, like I said I was unsure on If the form numbers would need to be Increased so the new forms can have numbers related to the ones that were already there. I'm not a maintainer, and I thought keeping parity with the code of the game(s) was generally desired, so I don't know

If this _doesn't matter_, the PR Is fine then

**Comment by Naramsim** [comment]
Ok! I'll be on vacation for 2 weeks or so and I don't know if I'll be able to merge everything while on vacation

**Comment by pokeapi-machine-user** [comment]
A [PokeAPI/api-data](https://github.com/PokeAPI/api-data) refresh has started. In ~45 minutes the staging branch of [PokeAPI/api-data](https://github.com/PokeAPI/api-data/tree/staging) will be pushed with the new generated data. <br><br> The staging branch will be deployed in our [staging environment](https://staging.pokeapi.co/api/v2/) and the entire API will be ready to review. <br><br> A Pull Request ([master](https://github.com/PokeAPI/api-data/tree/master)<-[staging](https://github.com/PokeAPI/api-data/tree/staging)) will be also created at [PokeAPI/api-data](https://github.com/PokeAPI/api-data/pulls) and assigned to the PokeAPI Core team to be reviewed. If approved and merged new data will soon be available worldwide at [pokeapi.co](https://pokeapi.co/api/v2/).

**Comment by pokeapi-machine-user** [comment]
The updater script has finished its job and has now opened a Pull Request towards [PokeAPI/api-data](https://github.com/PokeAPI/api-data/pulls) with the updated data. <br><br> The Pull Request can be seen deployed in our [staging environment](https://staging.pokeapi.co/api/v2/) when [CircleCI deploy](https://app.circleci.com/pipelines/github/PokeAPI/deploy) will be finished (_check the start time of the last build_).

**Pull request merged**
