### PR TITLE
Update Hasura to work on M1 Macs as well

### PR DESCRIPTION
**Pull request by campino2k**
This will make hasura make work on M1 Macs as well. See https://github.com/hasura/graphql-engine/issues/6337

This is the first fixed version.

### CODE REVIEW

**Comment by Naramsim** [comment]
Hi, are you familiar with Hasura? Is it worth upgrading to [2.15.2](https://github.com/hasura/graphql-engine/releases/tag/v2.15.2)?

**Comment by campino2k** [comment]
I'm not familiar and don't know, sorry. Just wanted to get it working on my work setup, thus chose the closest version.

**Comment by Naramsim** [comment]
Ok, did everything work with the version you just submitted?

**Comment by campino2k** [comment]
Not sure about "everything" but hasura works and using the same version CLI as described in the readme made a working Web interface and correctly ran `hasura apply`.

**Comment by campino2k** [comment]
Any news on this?

**Comment by Naramsim** [comment]
No news, Right now we don't have a buildable master, so we have to wait until we can test everything

**Comment by Naramsim** [comment]
Hi, I merged another PR that bumped hasura. Can you please update your `master` and test it?

**Pull request closed without merging**
