### PR TITLE
Add move table for Scarlet/Violet

### PR DESCRIPTION
**Pull request by giginet**
This PR is fixed version of this.
[Add move table for Scarlet/Violet by giginet · Pull Request #800 · PokeAPI/pokeapi](https://github.com/PokeAPI/pokeapi/pull/800)

I added `pokemon_moves` table for `version_group_id = 25` (Scarlet / Violet)

This table may work for all species and forms in SV.

### CODE REVIEW

**Comment by Naramsim** [comment]
Hi @giginet , Github says that you've done 35000 additions to the file. Is it right?

**Comment by giginet** [comment]
Yes. This PR contains all SV pokémons and moves matrix. So this have huge diffs.
It’s impossible to be reviewed by hunan eyes. But I tested this data in my product.

**Comment by Naramsim** [comment]
ok, I'll build it on my machine

**Comment by Naramsim** [comment]
tomorrow

**Comment by Naramsim** [comment]
Hi, in the `pokemon_moves.csv`, `level` is required. Do you have that info by chance?

**Comment by giginet** [comment]
I filled `level` only for `pokemon_move_method_id = 1` (Level moves)

Do you mean they should be `0` for other move_method moves?
(I think it should be nullable for not Level moves)

I'll fill all columns to `0`.

**Comment by giginet** [comment]
I filled all empty `level` columns to `0` on https://github.com/PokeAPI/pokeapi/pull/806/commits/1e57075a6b1add50239a9b769cc0c01f54d72366

**Comment by Naramsim** [comment]
Perfect! Having `0` is what we have right now for other _non-level_ moves. But I agree, it should be `null`-able.

**Comment by pokeapi-machine-user** [comment]
A [PokeAPI/api-data](https://github.com/PokeAPI/api-data) refresh has started. In 45 minutes the staging branch of [PokeAPI/api-data](https://github.com/PokeAPI/api-data/tree/staging) will be pushed with the new generated data. <br><br> The staging branch will be deployed in our [staging environment](https://staging.pokeapi.co/api/v2/) and you will be able to review the entire API. <br><br> A Pull Request ([master](https://github.com/PokeAPI/api-data/tree/master)<-[staging](https://github.com/PokeAPI/api-data/tree/staging)) will be also created at [PokeAPI/api-data](https://github.com/PokeAPI/api-data/pulls) and assigned to the PokeAPI Core team to be reviewed. If approved and merged new data will soon be available worldwide at [pokeapi.co](https://pokeapi.co/api/v2/).

**Pull request merged**
