### PR TITLE
Add and map Dream World sprites

### PR DESCRIPTION
**Pull request by Naramsim**
Ref: https://github.com/PokeAPI/pokeapi/pull/508

- Removes sprites from the repository
- Add https://github.com/PokeAPI/sprites as a submodule to this repository
- Maps new Dream World sprites to the API

```json
sprites: {
	back_default: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/133.png",
	...
	front_shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/133.png",
	front_shiny_female: null,
	other: {
		dream-world: {...sprites},
	}
},
```

Author: @C-Garza and @Naramsim

### CODE REVIEW

**Comment by Naramsim** [comment]
`deploy` step failed because the `master` branch was deployed and right now the `master` branch doesn't carry any new modifications:

```
100%|██████████| 99/99 [00:21<00:00,  4.54it/s]0:00, 2201.73it/s]
+ git add data
+ git config user.name pokeapi-machine-user
+ git config user.email pokeapi.co@gmail.com
+ git commit -m '[Updater Bot] Regenerate data'
On branch staging
nothing to commit, working tree clean
+ '[' 1 -ne 0 ']'
+ cleanexit fail 'Failed to run the pokeapi-updater container'
+ echo Exiting
```

We can merge even thus.

**Comment by Naramsim** [comment]
Seems to work: https://staging.pokeapi.co/api/v2/pokemon/wurmple

Can you double-check @C-Garza?

**Comment by C-Garza** [comment]
Looks like the sprites are working for me @Naramsim.

**Comment by Naramsim** [comment]
Hi @C-Garza, I just merged the PR 😄. Thanks for your contribution!

If you want we can keep work together and add new sprites. I was wondering if we should categorize even more the structure and follow something similar to https://pokemondb.net/sprites/bulbasaur

```
sprites: {
back_default: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/133.png",
...
front_shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/133.png",
front_shiny_female: null,
other: {
  dream-world: {...sprites},
  sugimori: {...sprites},
  ...
}
versions: {
  generation-i: {
	red: {...sprites},
	blue: {...sprites},
	yellow: {...sprites}
  },
  generation-ii: {
	crystal: {...sprites},
	gold: {...sprites},
	silver: {...sprites}
  },
  ...
```

**Comment by Naramsim** [comment]
And another observation: taking the example of Pokemon Red and Blue. Should we keep them separate or make a single `blu-red` (as we do in our https://pokeapi.co/api/v2/generation/1/)?

**Comment by C-Garza** [comment]
Thank you @Naramsim for helping me make my first contribution, you've been very helpful and responsive with all of my questions along the way 😄. 

I like the idea of structuring it by generations like that. And for the example of combining like `red-blue`, I think that's how the sprite folders are organized since I got them from Veekun. The only exception is generation 2 because `gold` and `silver` have different sprites.

So should I upload the version sprites next then to the sprites repo?

**Comment by Naramsim** [comment]
Yeah, maybe it's better to use the `red-blue` way. Let's try to add then the `red-blue` and `yellow` sprites. Can you please open a PR in our `sprites` repo with the data? I guess you can take the sprites from Veekun.

**Comment by Naramsim** [comment]
Ah, I also moved the `official-artwork` inside `Pokeapi/sprites` `/sprites/pokemon/other/official-artwork`. After we add the `yellow` and `red-blue` sprites we can update the API with all the new additions.

**Pull request merged**
