### PR TITLE
fix #423

### LINKED ISSUE #423: Duplicated pokemon-species in evolution-trigger #1
Dear PokeAPI team,

**https://pokeapi.co/api/v2/evolution-trigger/1/** contains Magnezone 4 times. At index 192, 262, 294 and 298.
Some others like leafeon and glaceon do also exist more than once.
Is it possible to reduce the linked species that every species appears only once?

### PR DESCRIPTION
**Pull request by Kronopt**

### CODE REVIEW

**Comment by Kronopt** [comment]
I'll fix this fix tomorrow

**Comment by cmmartti** [comment]
Fixes #423

**Comment by Kronopt** [comment]
I think you closed this instead of merging

**Comment by cmmartti** [comment]
Whoops! So I did. I don't have permissions to re-open, so I'll ask @Naramsim or @tdmalone to do that.

**Comment by cmmartti** [comment]
It won't let me re-open it though because it says the repository that submitted this PR has been deleted. Could you create a new PR?

**Comment by Kronopt** [comment]
Dammit...
Yeah, I deleted it because I thought everything was ok.
I'll open another

**Pull request closed without merging**
